### ISSUE TITLE
hg38 to hg19 performance

### ISSUE THREAD

**Issue by kokyriakidis** [milkschen/leviosam2#10]
Hi!

1. I would like to ask for your opinion. Do you think it is better to map to hg38_T2T_masked and then use leviosam2 to convert to hg19 or is it better to just map to hg19 from the beginning? I saw the improvements mapping from chm13v2 to hg19 but I am not so sure how well is the transition from hg38 to hg19.

2. What is the leviosam2 behavior on non primary and secondary alignments? Do you think I should remove them from the BAM file before lifting to another assembly?

KK

**Comment by milkschen** [comment]
1. Could you elaborate how you generate the `hg38_T2T_masked` reference? We tested the conversion from standard hg38 to hg19. The results were good but the improvements were not as substantial as `chm13->hg19`.
2. LevioSAM2 removes secondary and supplementary alignments during lift-over, so you don't need to filtering them prior to running the workflow.

**Comment by kokyriakidis** [comment]
I am considering an approace like this:
BWA --> indel realignment --> Leviosam2 --> Indel realignment. Do you thing the second indel realignment will help?

**Comment by milkschen** [comment]
If you're interested in running an indel realigner (I assume something like [ABRA2](https://academic.oup.com/bioinformatics/article/35/17/2966/5289536)), it should be fine to just run it after levioSAM2. In this way, the pipeline looks like 
```
BWA --> Leviosam2 --> Indel realignment
```

The following approach should also work, but I'd expect the above to perform slightly better.
```
BWA --> Indel realignment --> Leviosam2
```

In our experiments, we didn't specifically run an indel realigner after levioSAM2 (our pipeline looks like: `BWA --> LevioSAM2`). When calling variants, `GATK HaplotypeCaller` and `DeepVariant` both perform indel realignment.

**Comment by milkschen** [comment]
Sounds great. I hope you get great results!
