### ISSUE TITLE
Integrating strobealign for pe-mapping?

### ISSUE THREAD

**Issue by ksahlin** [milkschen/leviosam2#11]
Hi @milkschen,

I am interested in trying out levioSAM2 for [strobealign](https://github.com/ksahlin/StrobeAlign)'s regarding the SNP/indel call improvements (chm13 to hg38) as per your [thread](https://twitter.com/naechyun_chen/status/1531872594621628416?s=20&t=laBQ32Fm1PKCA9GKLljJCg) and recent [discussions](https://twitter.com/denizkural/status/1531751340699013120?s=20&t=laBQ32Fm1PKCA9GKLljJCg) on mapq scores on Twitter. 

[Strobealign is now on conda](https://anaconda.org/bioconda/strobealign), would it be possible to integrate it? This is not urgent as we will resume the development of our aligner (hence this analysis) after summer.

**Comment by milkschen** [comment]
Hi @ksahlin, Sure. I'd love to take a look. While I have limited bandwidth in June, I expect myself to have more time in July.

**Comment by ksahlin** [comment]
Sounds great to me. Thanks :)

**Comment by milkschen** [comment]
@ksahlin Thank you for developing the great tool! I've integrated strobealign for both se- and pe-mapping in the `leviosam2.sh` workflow.

**Comment by ksahlin** [comment]
Thanks @milkschen! We are soon releasing a new version of strobealign and I will have test  of `leviosam2` after that.
