### ISSUE TITLE
Updating conda and singularity with the latest version of leviosam2

### ISSUE THREAD

**Issue by zhemingfan** [milkschen/leviosam2#16]
Hi @milkschen,

If its okay, could you update Conda or Singularity with the latest version of leviosam2? I'm eager to try out some of the new `ONT` flag. I've been running into some issues with `cmake`

**Comment by milkschen** [comment]
Hi @zhemingfan, the ONT mode has been added in the latest version (v0.2.2), which is now available on conda/singularity/docker.
