### ISSUE TITLE
Error when running full workflow using `bwa mem`

### ISSUE THREAD

**Issue by jdidion** [milkschen/leviosam2#21]
The `samtools cat` step fails because the `committed` and `reailgned` BAM files have different headers. I think you want to use `samtools merge` rather than `cat`.

**Comment by milkschen** [comment]
Sorry for the late reply and thank you for pointing out this issue. Leviosam2 currently uses an updated chromosome index based on the source reference for `*-committed.bam`. The realigned results are based on the target reference. Therefore there is a mismatch in their headers, as you observed.

I plan to update the header for `*-committed.bam`. It's not hard to implement, but I'll need to find time to do more tests.
