### ISSUE TITLE
MAPQ of unmapped reads

### ISSUE THREAD

**Issue by canfirtina** [milkschen/leviosam2#33]
Hi @milkschen et al.,

I received the following error when using `picard MarkDuplicates` with the BAM files I lifted using leviosam2:

`ERROR::INVALID_MAPPING_QUALITY:Record 1, Read name ERR1938683.3, MAPQ should be 0 for unmapped read.`

Above is an example error message. I ran leviosam2 for around 20 different BAM files and the error is the same for all of them (except that the read name and the record number are different).

I checked the the corresponding record in the BAM file. Here is what I have for that particular record:

Before leviosam2:

`ERR1938683.3    99      chrI    1       60      29S121M =       37      183     CACCACACCCACACACCCACACACCACACCCACACCACACCCACACACCCACACACCACACCACACACCACACCACACCCCCACACACACATCCTAACACTACCCTAACACAGCCCTAATCTAACCCTCCCCAACCTGTCTCTCAACTTA BBB@BBBBBBBBGGGGFGGGGGEGGD222EEAECE2FGA1AEFGAE?FEGGCEAEGGGEEGDHAEEEE1GHHGGH11EE?/>EE/EEA/</BFCB2222FB??FC22GH2F/CA<C2<0?F1?1G0??///<0.<<001>1F=<G0<=0D NM:i:3  MD:Z:51A47G0G20 MC:Z:3S147M     AS:i:106        XS:i:51 RG:Z:ERR1938683`

After leviosam2

`ERR1938683.3    77      *       0       60      29S121M *       0       0       CACCACACCCACACACCCACACACCACACCCACACCACACCCACACACCCACACACCACACCACACACCACACCACACCCCCACACACACATCCTAACACTACCCTAACACAGCCCTAATCTAACCCTCCCCAACCTGTCTCTCAACTTA BBB@BBBBBBBBGGGGFGGGGGEGGD222EEAECE2FGA1AEFGAE?FEGGCEAEGGGEEGDHAEEEE1GHHGGH11EE?/>EE/EEA/</BFCB2222FB??FC22GH2F/CA<C2<0?F1?1G0??///<0.<<001>1F=<G0<=0D MC:Z:3S147M     AS:i:106        XS:i:51 RG:Z:ERR1938683 LO:Z:UM_UM`

Clearly this particular read could not be lifted after leviosam2. The issue is the old mapping quality is still there (and the CIGAR string), which is why MarkDuplicates is complaining. I can easily filter out the unmapped reads from my lifted BAM files to eliminate this issue, but I thought you may want to check this in case you consider this as an unwanted behavior for your tool.

Below is the script I use for running leviosam2. The `CHAIN` files are downloaded from UCSC.

```bash
PREFIX=$1
CHAIN=$2
BAM=$3
FAI=$4
THREAD=$5

leviosam2 index -c "${CHAIN}" -p "${PREFIX}" -F "${FAI}"
leviosam2 lift -C "${PREFIX}".clft -a "${BAM}" -p "${PREFIX}" -O bam -t ${THREAD}
```

**Comment by milkschen** [comment]
Thank you for reporting this issue comprehensively! This is a helpful finding.

I intentionally kept the non-flag fields and the tags to retain more information wrt the source alignments. Given the commonness of `picard MarkDuplicates`, I think it's reasonable for me to add a flag to clean the source reference info.

Before I update the software, I'd recommend you filter the unmapped reads so that your pipeline won't break.

Thank you 😀

**Comment by milkschen** [comment]
MAPQ for unliftable reads are set to 0 by default in v0.4.0.
