### ISSUE TITLE
"ERROR: ': ' is not a valid token in plain flow (unquoted) scalars - While using selective re-mapping

### ISSUE THREAD

**Issue by alisondiazc** [milkschen/leviosam2#34]
Hello! I was wondering if you could help me to solve an issue that I have while running leviosam2. When I try to make a liftover using the leviosam2.sh file I got this error: "ERROR: ': ' is not a valid token in plain flow (unquoted) scalars". I also notice that the program autocompletes mapq, aln_score & hdist as follow:
  Adding rule `mapq:30`
  Adding rule `aln_score:-10`
  Adding rule `hdist:100`
The code line I used was: 
`bash leviosam2.sh \
    -a minimap2 -g 1000 -H 100 -S -x /mnt/Timina/cgonzaga/adiaz/PacBio_secuencias/PYM007/8.Liftover/pacbio_all.yaml \
    -l map-hifi \
    -i /mnt/Timina/cgonzaga/adiaz/PacBio_secuencias/PYM007/8.Liftover/PYM007.T2T.pbmm2.bam \ 
    -o PYM007_T2TtoGRCh38_lifted \
    -f /mnt/Timina/cgonzaga/adiaz/PacBio_secuencias/PYM007/8.Liftover/Homo_sapiens_GRCh38.p14.noMT.fasta \
    -C /mnt/Timina/cgonzaga/adiaz/PacBio_secuencias/PYM007/8.Liftover/chm13v2-hg38.clft \
    -t 20`
I'm using the 0.2.2 version. I attach the log of the run in a text file
[logoftherun_liftover.txt](https://github.com/milkschen/leviosam2/files/10240553/logoftherun_liftover.txt)

**Comment by milkschen** [comment]
Hi @alisondiazc,

I tried your command, but I was not able to reproduce the error you posted.

Could you try to run the pipeline without `-x /mnt/Timina/cgonzaga/adiaz/PacBio_secuencias/PYM007/8.Liftover/pacbio_all.yaml` and see if that works? The error message looks to be related to YAML parsing. If without `-x` works, maybe try removing the quotes in `pacbio_all.yaml`. The realignment specification is important for the accuracy of the long read workflows.

**Comment by milkschen** [comment]
And by the way, please make sure the FASTA you used if identical to what we provided in the [case study](https://github.com/milkschen/leviosam2/tree/main/workflow). Or re-index it by yourself. A discordant FASTA and leviosam2 index (`.clft`) could result in errors.
