### ISSUE TITLE
leviosam2 for nanopore?

### ISSUE THREAD

**Issue by bluenote-1577** [milkschen/leviosam2#4]
Hi there,

Thanks for the cool software/preprint.

I'm wondering if there are good parameters for remapping nanopore reads, say error rates between 90-95% and lengths between 10 - 100kb? I see that there are workflows for HiFi reads, but I'm curious if parameters for nanopore reads have been tested. I tried the HiFi pipeline for nanopore reads and the results were not great. The default parameters for HiFI were too stringent, so I tried setting -H to 1000 and -G to 5000 but then there were issues with the remappings, especially around indels. 

I see no mention to ONT reads in the preprint, so maybe this isn't a priority, but I would be highly interested in such a solution.

Thanks!

**Comment by milkschen** [comment]
We haven't tested on ONT reads, since ultra-long ONT reads require moving the CIGAR information to the `CG:z` tag. I believe for typical-length ONT reads the workflow should work though. Around INDELs, we have the re-alignment module (`aln.cpp`) for localized re-alignment. A re-aligned read will have a `LR:i` tag, which shows its re-aligned score. Or maybe tweaking re-alignment parameters will help (see those presets in the `configs` directory).

Further, if your data is sharable, I'm happy to take a look.

**Comment by bluenote-1577** [comment]
Thanks for the quick response.

The ONT reads I'm using has the cigar information in the usual flag. I'm having trouble using the realignment workflow. The realignment workflow always puts all reads into the -unliftable.bam file. I tried using -g 500000 in the leviosam2.sh script but it still doesn't work.  Funnily enough, if I just use the leviosam2 lift command (which I assume doesn't do realignment) with -G set to the same large number then it works and not all reads are unliftable, but it has issues around indels.

I'm just using nanopore reads from the HPRC data, see https://github.com/human-pangenomics/HPP_Year1_Data_Freeze_v1.0

The data should be fairly generic nanopore reads. Let me know if you can get it to work.

**Comment by milkschen** [comment]
We now have an ONT mode (see #9 and #15). I will do more tests in the near future for ONT data. Just FYI.

**Comment by milkschen** [comment]
Hi @bluenote-1577, please check out our latest release (v0.2.2). That should work for typical ONT reads,

**Comment by jelber2** [comment]
What about ultra-long Nanopore reads with N50 >90kbp?

**Comment by jelber2** [comment]
Or maybe a better question if Ultra-long reads do not work, what is the maximum read length to split the ultra-long reads to? 25Kbp?

**Comment by milkschen** [comment]
Hi @jelber2 , The limitation is on the side of CIGAR strings. We use the standard BAM CIGAR field, so there can be at most 65535 (2 ** 16 - 1) operations.

**Comment by jelber2** [comment]
So, if there is a divergent, long read, it will throw an error or will it throw a warning and be discarded? Oh, just saw this https://github.com/lh3/minimap2?tab=readme-ov-file#working-with-65535-cigar-operations

**Comment by milkschen** [comment]
yes the `CG` tag is the ideal solution for ultra-long reads.
