### ISSUE TITLE
Updating docker container to 0.3.0

### ISSUE THREAD

**Issue by zhemingfan** [milkschen/leviosam2#41]
Hi @milkschen ,

The latest version is 0.2.2 on [dockerhub](https://hub.docker.com/r/naechyun/leviosam2/tags) (see compressed file size), but did you mean to update bump it to 0.3.0? Or is 0.3.0 an early developmental version?

**Comment by milkschen** [comment]
Hi @zhemingfan,

Thank you for raising this point. `latest` should be `v0.3.0` and has been updated. It should work well now.
