### ISSUE TITLE
how to index bam after liftover

### ISSUE THREAD

**Issue by zhoudreames** [milkschen/leviosam2#6]
i got the lifted_from_source.bam after liftover, but i dont obtained the index files for it.the error is showed in blow:

[E::hts_idx_push] Unsorted positions on sequence #1: 9031 followed by 5579
[E::sam_index] Read 'V350054331L4C002R03600248640' with ref_name='chrY', ref_length=47903866, flags=83, pos=5579 cannot be indexed
samtools index: failed to create index for "lifted_from_source.bam"

how to resolve it ? thanks~

**Comment by milkschen** [comment]
Could you try sorting the resulting BAM (`samtools sort`) and then building the BAM index (`samtools index`)?
