### ISSUE TITLE
Phasing after levioSAM2

### ISSUE THREAD

**Issue by oneeeeeehuang** [milkschen/leviosam2#63]
您好，謝謝您開發了如此具有突破性的軟體～
我們比較了單純hg002 align 到 GRCh38和 hg002 align 到  T2T-CHM13 並使用 levioSAM2 lift to GRCh38的座標系統後
分別跑phasing的結果，發現兩者產出VCF file完全相同
我們使用single-end workflow(minimap2 with Nanopore) :
bash leviosam2.sh \
    -a minimap2 -g 1500 -H 6000 -S -x ../configs/ont_all.yaml \
    -l map-ont \
    -i ont.bam \
    -o ont-lifted \
    -f grch38.fna \
    -C chm13v2-grch38.clft \
    -t 16 \
    -R suppress_annotations.bed # optional
levioSAM2 將座標系統進行了完美的轉換，但接下來的phasing 結果如同開頭所述
想請我們的作法(T2T-chm13v2 lift to GRCh38 with Nanopore long read, no ultra long read)對於下游SNP-only phasing的改善結果有是否限呢 ?

**Comment by milkschen** [comment]
請問您們用的 SNPs 是挑選過的嗎？或是 genome-wide?

在大部份的常用 SNPs 兩者相同是滿合理的，GRCh38 本來就是品質很好的 reference，在大部份的區域都表現很優秀，但如果整個 genome 都一樣的確是令人意外

**Comment by oneeeeeehuang** [comment]
我們使用的是 deepvariant call 出來的 SNP VCF file，沒有特別挑選過。

**Comment by milkschen** [comment]
了解，我們在 ONT 上的實驗主要是針對 SV，當初沒有看 ONT SNPs；我們有觀察到使用 PacBio HiFi long reads 在 SNP calling 上和 GRCh38 的差異不是非常巨大，我想在 ONT 上可能也是類似，不過結果完全一樣還是令人意外。

想請您檢查一下 `-R` 使用的 BED 檔案是哪一個？`chm13v2-grch38/chm13v2-grch38-source-unliftable-s_5000-winnowmap2-exc_1-shrink_15k.bed` 應該會比較適合 ONT。

此外，我也建議您比較看看 GRCh38 和 CHM13-to-GRCh38 的 VCF，看看有沒有比較明顯的不一樣。

**Comment by milkschen** [comment]
Close the issue for now since it doesn't look active. @oneeeeeehuang please re-open it if you have follow-up questions and/or comments. Thank you!

**Comment by oneeeeeehuang** [comment]
OK. Thank you!
