### ISSUE TITLE
Regarding time it takes to run leviosam2

### ISSUE THREAD

**Issue by Heather1999** [milkschen/leviosam2#68]
Thank you for developing this useful tool!
I am currently trying to lift a bam file mapped to CHM13 using bwamem2; I installed leviosam2 and changed its path then downloaded leviosam2.py. I tried the bash version last night but the task still wasn't finished the next morning so I changed to the python workflow. These are my parameters:
`-t 20 -i "/home/s/ASC_new/AS_02N.bam" -o "/home/s/ASC_new/AS_02N_lifted" -C "./t2t2hg38.clft" -f "/home/s/GRCH38/hg38_2.fa" -fi "/home/s/GRCH38/hg38_2.fai" --sequence_type ilmn_pe -a bwamem`
However it is still taking a long time; Is there any mistakes in my code or should I just do leviosam2 lift as insctructed on the README page?
Thank you!

**Comment by milkschen** [comment]
Is your BAM file sorted?

**Comment by Heather1999** [comment]
Thank you so much for replying!
Yes but it never generated a committed bam file anymore, just an unliftable one. I used leviosam2 lift and successfully generated a committed bam file. However, should I still go through baserecalibrator and the other downstream preprocessing? Because when I do baserecalibrator it errored with a warning "Input files reference and reads have incompatible contig".

**Comment by Heather1999** [comment]
Hi I solved this problem. I've been using the wrong chain file, the one in your resource file worked and generated compatible contig. Thank you, this issue can be closed:)

**Comment by milkschen** [comment]
Thank you! Please lmk if you have follow-up feedback :)

**Comment by Heather1999** [comment]
Hi, if I understanded it correctly, the leviosam2.py is supposed to re-align the differred bam file. I found that leviosam2 -lift generated a bam file with far less total read counts so I guess using the python workflow is the only way. However, the only output I got is an unliftable file, I did not see any final bam. I copy-pasted the command suggested, what could be wrong?
Thank you!
