### ISSUE TITLE
cpu utilization during lift

### ISSUE THREAD

**Issue by mrvollger** [milkschen/leviosam2#72]
Hello @milkschen!

I am using leviosam2 to lift some diploid alignments to h38, and I am noticing pretty poor CPU utilization (~5% per thread):
<img width="470" alt="image" src="https://github.com/milkschen/leviosam2/assets/6935283/d9dc9f01-3f5a-45ca-bd59-470f5af70678">
This could be an issue on my end, but I am not sure what. 

Any ideas? 

Thanks,
Mitchell

**Comment by mrvollger** [comment]
I just tried increasing `-T` to `-T 10000000` (and some more reasonable values in between) but I am not getting much improvement. 
<img width="469" alt="image" src="https://github.com/milkschen/leviosam2/assets/6935283/f908a1e7-c060-418c-a3f2-3c47c2504691">

**Comment by milkschen** [comment]
Hi @mrvollger !

Since each lift operation is fast, the bottleneck is IO and using many threads (>10) does not help. I mostly use 4 to 8 threads when using it myself. The thread scaling of leviosam2 is something we would like to improve.

**Comment by mrvollger** [comment]
Hi @milkschen,

Got it. You probably do, but just in case. Do you use multiple threads for decompressing and compressing in your htslib calls?

I am usually able to get ~2000% cpu on decompression/compression before IO is a problem on our HPC.

Thanks,
Mitchell

**Comment by milkschen** [comment]
Actually that might be the issue. I think I only parallelize the lift part. Thanks for mentioning it!

**Comment by mrvollger** [comment]
I am no good at C/C++ and usually use htslib through rust-htslib or pysam, but I think this is the relevant function:
https://github.com/samtools/htslib/blob/b204d55c88008ee2b1ef1267e30efa99842e0277/htslib/hts.h#L698-L707

**Comment by mrvollger** [comment]
I think I figured it out, I added just these two lines and now I am getting 3500% CPU usage of a total possible (5200%).

```diff
--- a/src/leviosam.cpp
+++ b/src/leviosam.cpp
@@ -360,6 +360,7 @@ void lift_run(lift_opts args) {
     samFile *sam_fp = (args.sam_fname == "")
                           ? sam_open("-", "r")
                           : sam_open(args.sam_fname.data(), "r");
+    hts_set_threads(sam_fp, 16);
     if (!sam_fp) {
         std::cerr << "[E::lift_run] Invalid alignment input\n";
         exit(1);
@@ -373,6 +374,8 @@ void lift_run(lift_opts args) {
     samFile *out_sam_fp = (args.outpre == "-" || args.outpre == "")
                               ? sam_open("-", out_mode.data())
                               : sam_open(out_sam_fname.data(), out_mode.data());
+    hts_set_threads(out_sam_fp, 16);
+
     if (!out_sam_fp) {
         std::cerr << "[E::lift_run] Invalid alignment output\n";
         exit(1);
```

**Comment by mrvollger** [comment]
I would make a PR that properly exposes these to the command line, but tbh I got lost in the argument parsing.

**Comment by mrvollger** [comment]
Actually, it is even better than I thought after it ramped up, basically totally maxing out the CPUs :) 
<img width="1433" alt="image" src="https://github.com/milkschen/leviosam2/assets/6935283/2fd2f734-a139-4070-8ea5-0b6780036381">

**Comment by milkschen** [comment]
Thanks again for raising the issue and proposing the solution! This issue has been addressed.
